apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - image: ghcr.io/ntrada/klassresan:sha256-98edfe090f3625af0065b258729314a85f1ea2abb06aa0c2b88df5fc863bc985.sig
        name: api-gateway
        ports:
        - containerPort: 80
