apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  template:    
    spec:
      containers:
      - name: api-gateway
      - image: docker.io/wahlgrena/api-gateway:develop        
        ports:
        - containerPort: 80
