apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
spec:
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - image: docker.io/wahlgrena/api-gateway:develop        
        ports:
        - containerPort: 80
