apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: local-
resources:
- ../../base

configMapGenerator:
- envs:
  - api-gateway/config/config.properties
  name: gateway-config
labels:
- includeSelectors: true
  pairs:
    environment: local
patches:
- path: api-gateway/ingress-patch.yaml

images:
  - name: wahlgrena/api-gateway:local
    newName: wahlgrena/api-gateway
    newTag: local
