apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:
  environment: local
namePrefix: local-

resources:
  - ../../base

patchesStrategicMerge:  
  - api-gateway/ingress-patch.yaml

configMapGenerator:
  - name: gateway-config
    envs:
      - api-gateway/config/config.properties

