apiVersion: apps/v1
kind: Deployment
metadata:
  name: consul
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: consul
  template:
    metadata:
      labels:
        app: consul
    spec:
      containers:
      - image: docker.io/wahlgrena/api-gateway:1
        name: consul
        ports:
        - containerPort: 80
