apiVersion: v1
kind: Service
metadata:
  name: api-gateway
  labels:
    prometheus: monitoring
spec:
  type: ClusterIP
  ports:
    - name: app-port
      port: 80
      targetPort: 80
  selector:
    name: api-gateway