apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-gateway/deployment.yaml
  - api-gateway/service.yaml  
  - api-gateway/hpa.yaml

images:
  - name: docker.io/wahlgrena/api-gateway:develop
    newName: wahlgrena/api-gateway
    newTag: 1.0.1