apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namePrefix: dev-

commonLabels:
    app: api-gateway
    env: dev

bases:
  - ../../../base

resources:
  - ingress.yaml

patchesStrategicMerge:
  - deployment.yaml
  - ingress.yaml

namespace: dev