apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namePrefix: dev-



resources:
- ingress.yaml
- ../../base

namespace: dev
labels:
- includeSelectors: true
  pairs:
    app: api-gateway
    env: dev
patches:
- path: deployment.yaml
- path: ingress.yaml
