apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-to-gateway
spec:
  rules:
    - http:
        paths:
          - path: /dev-gateway(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: api-gateway.dev
                port:
                  number: 80